//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scheduleHelp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LessonsTime
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LessonsTime()
        {
            this.Schedules = new HashSet<Schedules>();
        }
    
        public int id { get; set; }
        public Nullable<System.TimeSpan> timestart { get; set; }
        public Nullable<System.TimeSpan> timestop { get; set; }
        public string corpus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedules> Schedules { get; set; }
    }
}
