//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scheduleHelp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedules
    {
        public int id { get; set; }
        public Nullable<int> subjectnameid { get; set; }
        public Nullable<int> groupid { get; set; }
        public Nullable<int> roomid { get; set; }
        public Nullable<int> dayid { get; set; }
        public Nullable<int> week_colorid { get; set; }
        public Nullable<int> lessonstimeid { get; set; }
        public Nullable<int> subgroup { get; set; }
        public Nullable<int> teacherid { get; set; }
    
        public virtual Days Days { get; set; }
        public virtual Groups Groups { get; set; }
        public virtual LessonsTime LessonsTime { get; set; }
        public virtual Rooms Rooms { get; set; }
        public virtual Subjects Subjects { get; set; }
        public virtual Teachers Teachers { get; set; }
        public virtual WeekColors WeekColors { get; set; }
    }
}
